name: Deploy

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Run codes
        shell: bash
        run: |
          pip install -r requirements.txt
          python cn.py
      - name: Pack
        run: |
          rm -rf public
          mkdir -p public
          mv cn.json public/
      - name: Deploy github pages
        # https://github.com/marketplace/actions/github-pages-action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
#      - name: Purge CDN cache
#        shell: bash
#        run: |
#          curl https://purge.jsdelivr.net/gh/RyoLee/cn_working_day@gh-pages/cn.json
